### ISSUE TITLE
context is not passed from page.ShowModal() but from the frame.navigate()

### ISSUE THREAD

**Issue by tcrgit** [NativeScript/modal-navigation-demo#4]
The second (context) parameter parameter of page.showModal is not passed in this example.
```
    page.showModal(frame,
        "context", 
        () => console.log("home-page modal frame closed"),
        true);
    );
```
If a frame is supplied to page.showModal, the frame.navigate() must contain the context, e.g. either:
```
   frame.navigate({moduleName: "modal/modal-page", context: "Context"}); 
   frame.navigate({moduleName: "modal/modal-page", context: { someContext: "Context", moreContext: "Context2" } });
```
The callback and fullscreen parameters work still work as expected. This appears to be be due to the shift to allowing navigation within modals/ multiple modals.

**Comment by vchimev** [comment]
Follow https://github.com/NativeScript/NativeScript/issues/6271.
